### ISSUE TITLE
KMODE_EXCEPTION_NOT_HANDLED

### ISSUE THREAD

**Issue by soltrac** [wbenny/hvpp#12]
Crash when I try to load the driver:

Windows 10 Rs4
Intel i3-22230 CPU

**Comment by wbenny** [comment]
Most likely fixed by latest commit. Please, try again with recent master. If problem persists, upload crashdump somewhere with your .sys & .pdb files so I could further investigate your problem.

**Comment by soltrac** [comment]
As you told, fixed in last commit. Can close this.
