### ISSUE TITLE
Won't compile with Visual Studio 2017

### ISSUE THREAD

**Issue by DebugBuggin** [wbenny/hvpp#18]
I upgraded to 2017 and got the latest SDK ( 10.0.17763.0 ) and compiling this project is tons of errors and 3 out of 4 projects fail. I have to target to latest SDK and that doesn't fix anything, lot of constexpr errors and other things. This is such a fascinating project and was really looking forward to testing it out, if you know of way to get this compiling please share.

**Comment by wbenny** [comment]
Did you try to retarget the solution to 10.0.17763.0? The project compiles fine.

**Comment by DebugBuggin** [comment]
> Did you try to retarget the solution to 10.0.17763.0? The project compiles fine.

yeah I did, I tried retargeting for a bunch of different SDK's I have installed, just bunch of errors, only the usermode project compiles. I compile other drivers all the time. I just uninstalled everything(VS2015 and VS2017, all SDKS) and just reinstalled VS2017 + WDK. Still nothing, if you're willing to help me get this working i'll paypal or bitcoin you $20. My email is marketdev8@gmail, can chat after on discord or whatever. BTW i'm on 1803 win10 and have latest gen intel cpu.

**Comment by wbenny** [comment]
I know that 1809 WDK had some issues when I tried it some weeks ago - I couldn't compile any driver without fixing some .target files, but that turned out to be bug in the WDK itself. As for your situation - I'm sorry but I think it has something to do with your state of SDK/WDK, and not this project per se.

**Comment by DebugBuggin** [comment]
yeah I tried 1803 WDK as well. Ahh closed the thread on me? Damn, alright...

**Comment by wbenny** [comment]
Also note that uninstalling WDK can leave some files and SDK included in VS is not always necessarily "friendly" with standalone Windows SDKs. Therefore, uninstalling everything and installing again might not always help and some manual hackery is needed.

**Comment by DebugBuggin** [comment]
I got it to compile! I removed visual studio 2015 and its sdk/wdk's and reinstall vs2017 and sdk+wdk. Play around more with the framewok version in project properties and finally works. I think maybe have vs2015 stuff along side 2017 was part of the issue, not sure.

**Comment by wbenny** [comment]
Nice one! :)

**Comment by DebugBuggin** [comment]
i'll still btc you $10 if you want, even though closed thread on me :D I appreciate the project, this will go long way in me understanding hypervisors more. Send me BTC address,if you don't have one jaxx is a really nice, easy, fast, free client for cryptocurrencies.

**Comment by wbenny** [comment]
This is completely on you. My BTC address is always at the bottom of the README.md of each of my project.

**Comment by DebugBuggin** [comment]
Ahh clever, and done, thanks mate.
