### ISSUE TITLE
ZW hooking

### ISSUE THREAD

**Issue by DebugBuggin** [wbenny/hvpp#19]
The usermo example works great. Would kernel hooking be difficult to do with this project? Also just a side unrelated note I had disable CPU overclocking in my bios to stop some random bluescreens that would show.

**Comment by wbenny** [comment]
Hooking of kernel functions isn't really _that_ difficult and there are multiple ways on how to achieve that. 
There's already issue on this: https://github.com/wbenny/hvpp/issues/7 I'm planning to push some of them in the master repo sometime in the future. Until then, you can take inspiration from another projects.

**Comment by DebugBuggin** [comment]
Ok great, also thanks again for this project, is pretty much the first i've seen that does usermo, when I found this repo was almost like Christmas for me :D, couldn't believe it, anyway i'll stop spamming your comments and get to work.

**Comment by wbenny** [comment]
https://github.com/tandasat/FU_Hypervisor already did that before hvpp :)

**Comment by wbenny** [comment]
And thanks for appreciation. I appreciate that. :)
