### ISSUE TITLE
Hypervisor detect

### ISSUE THREAD

**Issue by DebugBuggin** [wbenny/hvpp#21]
this article shows few methods to detect hypervisor. https://rayanfam.com/topics/defeating-malware-anti-vm-techniques-cpuid-based-instructions/

Inside HvppHandleExecuteCpuid I do the following to set the 31st bit to 0
```
else if(Context->Eax == 1)
	{
		 Context->Ecx |= 0UL << 30;
	}
```

but this breaks chrome, firefox and many others, they won't connect to the internet. Do you why and a way to fix it?

update: appears it breaks apps regardless if I set anything, I have to cal HvppVmExitPassthrough(Passthrough); but then the context registers aren't set.

**Comment by wbenny** [comment]
1. `0ULL << 30` results in 0. You literally leave Ecx unchanged.
2. Your intention is probably to call __cpuid and THEN modify the bit in Ecx. Not just modify Ecx.

**Comment by DebugBuggin** [comment]
my intention is to set 0 to the 31bit of ecx if eax == 1 when someone else calls cpuid; I've done this successfully with your HvppHandleExecuteCpuid callback and tested with usermod app, but my issue is even if I modify no registers it breaks all browser say for example

```
else if(Context->Eax == 1)
	{

	}

```
without calling HvppVmExitPassthrough(Passthrough);  breaks internet. If I call that function then it doesn't matter if I set context register or not because it doesn't set anything.

**Comment by wbenny** [comment]
This is probably because Chrome expects some valid CPUID output in the registers, meanwhile you leave there garbage (unchanged).

**Comment by DebugBuggin** [comment]
you fixed it! thank you, for everyone you can spoof this hypervisor check with the following

```
	else if(Context->Eax == 1)
	{
		int cpui[4];
		__cpuid(cpui, 0);
		Context->Eax = cpui[1];
		Context->Ebx = cpui[2];
		Context->Edx = cpui[4];
		Context->Ecx |= 0UL << 30;
	}
```

**Comment by wbenny** [comment]
I just want to point out again, that `0ULL << 30` results in 0. Your intention is probably to do `Context->Ecx &= ~(1ULL << 31)` to actually **unset** the 31st bit.

**Comment by DebugBuggin** [comment]
the 0UL << 30 worked in testing just now, testing on and off, but will try your way, thanks

**Comment by wbenny** [comment]
It worked probably because the bit wasn't even set in the first place. :)
