### ISSUE TITLE
HostCr3 Bug

### ISSUE THREAD

**Issue by fake-cheater** [wbenny/hvpp#27]
The initialization routine using Ipi will run in a random context. So it can cause a blue screen. You should save cr3 in the system context(DriverEntry ) and set it in vcpu init

void vcpu_t::setup_host() noexcept
{
...///
  host_cr0(read<cr0_t>());
  host_cr3(read<cr3_t>());->>  host_cr3(dq_savedSystemCr3);
  host_cr4(read<cr4_t>());

  cr3_t cr3 = read<cr3_t>();
  DbgPrint("Host Cr3:%p\n", cr3.flags);

**Comment by fake-cheater** [comment]
Manual map Load
DriverEntry->pscreatesystemthread -->ipiCall InitVcpu ->Cr3 ==System Cr3
DriverIoctl>pscreatesystemthread -->ipiCall InitVcpu ->Cr3 ==Random Cr3
wtf...

**Comment by wbenny** [comment]
Interesting, I would swear to god that I've read somewhere that IPI callbacks are always executed within the system context. But now that I've been looking everywhere, I can't find it. :) Also I've never experienced such BSOD myself yet (and I run it dozens of times daily).

I'll fix it.

**Comment by fake-cheater** [comment]
I am very sorry. It is my mistake.
So I closed the question after checking it last night.
sorry..
