### ISSUE TITLE
Possible bug in vcpu_t::entry_host()

### ISSUE THREAD

**Issue by RangeMachine** [wbenny/hvpp#29]
You capturing rip rsp and rflags before vmexit handler:
`    auto captured_rsp    = exit_context_.rsp;
    auto captured_rflags = exit_context_.rflags;

    {
      exit_context_.rsp    = guest_rsp();
      exit_context_.rip    = guest_rip();
      exit_context_.rflags = guest_rflags();

      //
      // WinDbg will show full callstack (hypervisor + interrupted application)
      // after these two lines are executed.
      // See vcpu.asm for more details.
      //
      // Note that machine_frame.rip is supposed to hold return address.
      // exit_instruction_length() is added to the guest_rip() to create
      // this value.
      //
      stack_.machine_frame.rip = exit_context_.rip + exit_instruction_length();
      stack_.machine_frame.rsp = exit_context_.rsp;

      {
        handler_->handle(*this);`
As result any modifications to rip, rsp and rflags in vmexits have not any effect. So possible solution is:
`    memory_manager::allocator_guard _;

    auto captured_rsp    = exit_context_.rsp;
    auto captured_rflags = exit_context_.rflags;

    {
	  handler_->handle(*this);

      exit_context_.rsp    = guest_rsp();
      exit_context_.rip    = guest_rip();
      exit_context_.rflags = guest_rflags();`

**Comment by wbenny** [comment]
I'm not sure what do you mean. The code is there : https://github.com/wbenny/hvpp/blob/ec4115e5af113d5b7fa57735cfc7ea85f6dad47c/src/hvpp/hvpp/vcpu.cpp#L673

**Comment by RangeMachine** [comment]
Look. We are capturing` exit_context_.rip    = guest_rip();` before ` handler_->handle(*this);`. If you do something like `vmwrite(guest_ip, newip)` in vmexit handler, it will not have any effect because after vm exit we are restoring captured rip `guest_rsp(exit_context_.rip);`.

**Comment by wbenny** [comment]
That's true. The idea here is that you can change the registers via vp.exit_context(). Including rip, rsp & rflags

**Comment by RangeMachine** [comment]
Thanks for hint.
