### ISSUE TITLE
hvppdrv.sys file isn't created

### ISSUE THREAD

**Issue by noobie-cod** [wbenny/hvpp#32]
After building the hvpp.cpp file on visual studio on test mode, the hvppdrv.sys file is not created and not found on the folder. Help me in solving this issue

**Comment by wbenny** [comment]
Can you give me more details?

**Comment by noobie-cod** [comment]
sc create hvpp type= kernel binPath= "C:\full\path\to\hvppdrv.sys"

To execute this command we need the complete path to the hvppdrv.sys file, I cannot find this particular file in the source folder

**Comment by wbenny** [comment]
Does it compile successfully? If so, the Visual Studio should tell you the full path to the `.sys` in the Output window after compilation. The compiled files should be located in `bin\x64\Debug` or `bin\x64\Release` directory.

**Comment by noobie-cod** [comment]
hvpp.vcxproj -> C:\hvpp-master\bin\x64\Debug\hvpp.lib

This is the output I am getting after successful compilation. Is this the same file?

**Comment by wbenny** [comment]
In README.md, there is:

```
...
### Code workflow

> Note: **hvpp** is compiled as a static library, which is linked with the **hvppdrv** project.
...
```

Did you try to compile `hvppdrv` project?

**Comment by noobie-cod** [comment]
Error	MSB4018	The "SignTask" task failed unexpectedly.
System.Security.Cryptography.CryptographicException: Access is denied.	

I am getting this error after compiling the hvppdrv file

**Comment by wbenny** [comment]
This looks like problem with your VS installation, not hvpp.

Quick googling recommended running VS as Administrator: https://stackoverflow.com/questions/36223909/msbuild-error-msb4018the-signtask-task-failed-unexpectedly-in-vs2015

**Comment by noobie-cod** [comment]
Thank you so much for your help. Issue resolved.
