### ISSUE TITLE
Cannot trap rdtsc

### ISSUE THREAD

**Issue by chongg** [wbenny/hvpp#33]
Hello. I try to trap rdtsc

I add to vmexit_custom.h
```
void handle_execute_rdtsc(vcpu_t& vp) noexcept override;
```

and to vmexit_custom.cpp
```
void vmexit_custom_handler::handle_execute_rdtsc(vcpu_t& vp) noexcept
{
  DbgPrint("rdtsc");
  base_type::handle_execute_rdtsc(vp);
}
```

But am never catch the instruction. What am do wrong sir?

**Comment by wbenny** [comment]
Hi, you probably forgot to set `rdtsc_exiting` bit in `vmx_procbased_ctls`?

**Comment by chongg** [comment]
Yes I am forget! Thank you kind sir! Your project is very beautiful for my eyes :)
