### ISSUE TITLE
BSOD when running vmware 15.0.2

### ISSUE THREAD

**Issue by arnerak** [wbenny/hvpp#36]
I'm getting a BSOD CLOCK_WATCHDOG_TIMEOUT when starting a vmware vm whilst hvpp is running. 
Is this unsupported?

**Comment by wbenny** [comment]
Do you mean your PC gets BSOD or the VM?

**Comment by arnerak** [comment]
PC. Unfortunately, no memory dump is created, the pc just reboots. Occasionally, the system just freezes instead of bsoding.

**Comment by wbenny** [comment]
Interesting. Is your PC overclocked? Running hvpp in VMware is supported - as a matter of a fact, that's how I primarily develop it.

**Comment by arnerak** [comment]
PC components are not overclocked. I don't have trouble running hvpp inside a VMware VM. The problem is a system freeze/crash the moment a second hypervisor is started (does not matter if I run hvpp or VMware first). The same setup does work with HyperPlatform.

**Comment by wbenny** [comment]
Aha, now I got it - you mean running hvpp and VMware side by side. Yep that scenario (or any scenario involving two hypervisors) is untested and currently not supported.

**Comment by arnerak** [comment]
Ok. Thank you for the fast responses!
