### ISSUE TITLE
[hvppdrv] Unloading is currently broken

### ISSUE THREAD

**Issue by Benno1308** [wbenny/hvpp#40]
Hey there,
Commit a59f7cc0b905ecf8b378ccd4bccc24b2ca765c0f seems to have broken HV unloading,
its still working in 4404207c220768974963aae97286e95202f55926.

Crash: SYSTEM_PTE_MISUSE
VM: VMware Workstation 15.0.2 build-10952284
Guest OS: Windows 8.1 Pro, 64-bit  (Build 9600) 6.3.9600
Guest CPU: i9 7980XE, 4 vCores
Guest RAM: 6.1GB(Intentionally using 6208MB instead of 6144MB)

**Comment by wbenny** [comment]
Hey, never got such crash, but I probably know where it's coming from. Can you provide dump + PDBs, please?

**Comment by wbenny** [comment]
Fixed in master (...and sorry for the `git push -f`)
